#!/bin/sh
. "$(dirname $0)/_/husky.sh"

# Re-apply original unstaged changes
if [ -e ./.husky/_/stashed ]; then
  bash -c "if [[ \$(git stash list) ]]; then git stash pop -q; fi"
  rm ./.husky/_/stashed
else
  echo "pre-commit did not stash anything, passing..."
fi
